### PR TITLE
Copy ignore-2.12.txt to ignore-2.13.txt

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Relates to https://github.com/ansible-collections/overview/issues/45#issuecomment-926794724

### CODE REVIEW

**Comment by Andersson007** [comment]
cc @carchi8py please see the recent updates in the Changes impacting issue starting with https://github.com/ansible-collections/overview/issues/45#issuecomment-923507542

**Comment by carchi8py** [comment]
Just got back from vacation, i'll look to the devel changes and make them

**Comment by carchi8py** [comment]
@Andersson007 i'm assuming the error i'm seeing in our unit test is related to ansible-collections/overview#45 but I'm not sure how to fix It. This had been working find in devel until last week (so I'm assuming it related to the above)
I've tried pip install request and python -m pip install request as mentioned in that story but those both introduced more errors. 

AnsibleFailJson: {'msg': "Failed to import the required Python library (requests) on 3d84fc88185d's Python /usr/bin/python2.6. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter", 'failed': True}

**Comment by Andersson007** [comment]
@carchi8py i can't take a look now as the summit and the hackathon take place this week. Will see later, maybe next week.

How about creating an issue would be nice (linked to this PR and the announcement pinging the folks who posted them)?

**Review by lonico — APPROVED** [review]

**Pull request merged**
